### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by sethlwilson** [takezoe/atom-character-count#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: [character-count](https://github.com/takezoe/atom-character-count) package, v1.0.2
### Stack Trace

Uncaught TypeError: Cannot read property 'getText' of undefined

```
At /Users/sethwilson/.atom/packages/character-count/lib/character-count.coffee:4

TypeError: Cannot read property 'getText' of undefined
  at Object.module.exports.count (/Users/sethwilson/.atom/packages/character-count/lib/character-count.coffee:4:34)
  at atom-workspace.<anonymous> (/Users/sethwilson/.atom/packages/character-count/lib/character-count.coffee:7:70)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -1:41.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:14.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:00.5.0 character-count:count (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
character-count, v1.0.2
pretty-json, v0.3.3

# Dev
No dev packages
```

**Comment by takezoe** [comment]
@sethwilsonwishabi Sorry for my slow response. Fixed and published v1.0.3.
